- name: Create stop-sync shell file.
  template:
    src: "{{ aem_cms_stop_sync_template }}"
    dest: "{{ aem_cms_stop_sync_path }}"
    owner: "{{ aem_cms_user }}"
    group: "{{ aem_cms_group }}"
    mode: "0744"

- name: Create AEM systemd unit file.
  template:
    src: "{{ aem_cms_systemd_unit_template }}"
    dest: "/etc/systemd/system/{{ aem_cms_service_name }}.service"
    mode: "0644"

- name: Enable AEM service.
  systemd:
    name: "{{ aem_cms_service_name }}"
    enabled: yes
    daemon_reload: yes
