---
- name: Install setuptools package.
  package:
    name: python-setuptools

- name: Install pip.
  easy_install:
    name: pip
    state: latest
  tags:
    - skip_ansible_lint

- name: Install boto3 dependency.
  pip:
    name: boto3

- name: Download AEM artifact from S3.
  s3:
    bucket: "{{ aem_cms_s3_bucket }}"
    object: "{{ aem_cms_s3_object }}"
    dest: "{{ aem_cms_download_path }}/{{ aem_cms_quickstart_name }}"
    mode: get
    aws_access_key: "{{ aem_cms_s3_access_key | default(omit) }}"
    aws_secret_key: "{{ aem_cms_s3_secret_key | default(omit) }}"

- name: Set user and group for downloaded AEM artifact.
  file:
    path: "{{ aem_cms_download_path }}/{{ aem_cms_quickstart_name }}"
    owner: "{{ aem_cms_user }}"
    group: "{{ aem_cms_group }}"